### ISSUE TITLE
Literaturverzeichnis / Detail View for Bibliograhpic Items

### ISSUE THREAD

**Issue by csae8092** [freud-digital/frd-static#4]
transform `listbild.xml` into something similar as `listperson.xm|html` https://freud-digital.github.io/frd-static/listperson.html, i.e. a sortable, filterable table (like) thing where I can click one entry and I get to another page -> the detail view page of a bibliographic item (with more information as in the table/listview) and a list of all freud-werke where this bibliograhpic item is mentioned

**Comment by linxOD** [comment]
0f3f8557b5168f2c6554dc3ce1f3e079417e1bd5
